<tr id="row_dss_disableregistration_restriction_setting">
    <td colspan="5">
        <div class="section-config">
            <div class="entry-edit-head admin__collapsible-block">
                <?= /* @noEscape */ __('If you need the complete restriction functionality for your store in
                different ways (disabling registration, requiring customer approval, restricting access to
                special customers while allowing guest access to certain pages), please visit') ?>
                <a href="mailto:info@digitsoftsol.com">
                    <?= /* @noEscape */ __('Need Support? Contact us') ?>
                </a>
            </div>
        </div>
    </td>
</tr>