<?php
/**
 * New Customer block template
 *
 * @var $block \Magento\Customer\Block\Form\Login\Info
 */
?>
<div class="block block-new-customer">
    <div class="block-title">
        <strong id="block-new-customer-heading" role="heading" aria-level="2">
            <?= $escaper->escapeHtml(__('New Customers')) ?>
        </strong>
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <p>
            <?= $escaper->escapeHtml($block->getMpRegistrationDisabledMessage()) ?>
        </p>
    </div>
</div>